//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestAritmetica.srvAritmetica {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAritmetica")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnitTestAritmetica.srvAritmetica.clsAritmetica))]
    public partial class BaseRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsAritmetica", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceAritmetica")]
    [System.SerializableAttribute()]
    public partial class clsAritmetica : UnitTestAritmetica.srvAritmetica.BaseRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroA {
            get {
                return this.numeroAField;
            }
            set {
                if ((this.numeroAField.Equals(value) != true)) {
                    this.numeroAField = value;
                    this.RaisePropertyChanged("numeroA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroB {
            get {
                return this.numeroBField;
            }
            set {
                if ((this.numeroBField.Equals(value) != true)) {
                    this.numeroBField = value;
                    this.RaisePropertyChanged("numeroB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((this.resultadoField.Equals(value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvAritmetica.IWSaritmetica")]
    public interface IWSaritmetica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSaritmetica/sumar", ReplyAction="http://tempuri.org/IWSaritmetica/sumarResponse")]
        UnitTestAritmetica.srvAritmetica.clsAritmetica sumar(int numero1, int numbero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSaritmetica/sumar", ReplyAction="http://tempuri.org/IWSaritmetica/sumarResponse")]
        System.Threading.Tasks.Task<UnitTestAritmetica.srvAritmetica.clsAritmetica> sumarAsync(int numero1, int numbero2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSaritmeticaChannel : UnitTestAritmetica.srvAritmetica.IWSaritmetica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSaritmeticaClient : System.ServiceModel.ClientBase<UnitTestAritmetica.srvAritmetica.IWSaritmetica>, UnitTestAritmetica.srvAritmetica.IWSaritmetica {
        
        public WSaritmeticaClient() {
        }
        
        public WSaritmeticaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSaritmeticaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSaritmeticaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSaritmeticaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitTestAritmetica.srvAritmetica.clsAritmetica sumar(int numero1, int numbero2) {
            return base.Channel.sumar(numero1, numbero2);
        }
        
        public System.Threading.Tasks.Task<UnitTestAritmetica.srvAritmetica.clsAritmetica> sumarAsync(int numero1, int numbero2) {
            return base.Channel.sumarAsync(numero1, numbero2);
        }
    }
}
